# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # Clean up go.mod and download deps
    - go mod tidy
    # Run go generate if needed
    - go generate ./...

builds:
  - id: default
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: "{{ .ProjectName }}"
    ldflags:
      - "-s -w"
    mod_timestamp: ""

archives:
  - id: default
    builds:
      - default
    format: tar.gz
    replacements:
      darwin: Darwin
      amd64: x86_64
      arm64: arm64
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - docs/**
      - design/**/*.png
      - templates/**/*
      - ex*.txt
      - cloaking-*.txt
      - localhost.pem
      - d*.toml
      - utils/**/*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}_v{{ .Arm }}{{ end }}"

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
